RAW_DATASET = r"..."
OUTPUT_FOLDER_DATASET = r"..."

# Dataset ridotti
DATASET_10K = f"{OUTPUT_FOLDER_DATASET}cars_10k"
DATASET_100K = f"{OUTPUT_FOLDER_DATASET}cars_100k"
DATASET_500K = f"{OUTPUT_FOLDER_DATASET}cars_500k"
DATASET_1M = f"{OUTPUT_FOLDER_DATASET}cars_1M"
DATASET_FULL = f"{OUTPUT_FOLDER_DATASET}cars_full"
DATASET_FULL_X2 = f"{OUTPUT_FOLDER_DATASET}cars_full_x2"
DATASET_FULL_X3 = f"{OUTPUT_FOLDER_DATASET}cars_full_x3"
DATASET_FULL_X5 = f"{OUTPUT_FOLDER_DATASET}cars_full_x5"