from pandas.api.types import CategoricalDtype

dtype_spec = {
    'vin': str,
    'back_legroom': str,
    'bed': str,
    'bed_height': str,
    'bed_length': str,
    'body_type': CategoricalDtype(),
    'cabin': str,
    'city': str,
    'city_fuel_economy': float,
    'combine_fuel_economy': float,
    'daysonmarket': 'Int64',  # Usiamo Int64 per supportare NaN
    'dealer_zip': str,  # Codice postale come stringa
    'description': str,
    'engine_cylinders': str,
    'engine_displacement': float,
    'engine_type': str,
    'exterior_color': str,
    'fleet': 'boolean',
    'frame_damaged': 'boolean',
    'franchise_dealer': 'boolean',
    'franchise_make': str,
    'front_legroom': str,
    'fuel_tank_volume': str,
    'fuel_type': str,
    'has_accidents': 'boolean',
    'height': str,
    'highway_fuel_economy': float,
    'horsepower': float,
    'interior_color': str,
    'isCab': 'boolean',
    'is_certified': 'boolean',
    'is_cpo': 'boolean',
    'is_new': 'boolean',
    'is_oemcpo': 'boolean',
    'latitude': float,
    'length': str,
    'listed_date': str,  # Poi convertiremo in datetime
    'listing_color': str,
    'listing_id': int,
    'longitude': float,
    'main_picture_url': str,
    'major_options': str,
    'make_name': str,
    'maximum_seating': str,
    'mileage': float,
    'model_name': str,
    'owner_count': 'Int64',
    'power': str,
    'price': float,
    'salvage': 'boolean',
    'savings_amount': float,
    'seller_rating': float,
    'sp_id': str,
    'sp_name': str,
    'theft_title': 'boolean',
    'torque': str,
    'transmission': str,
    'transmission_display': str,
    'trimId': str,
    'trim_name': str,
    'vehicle_damage_category': str,
    'wheel_system': str,
    'wheel_system_display': str,
    'wheelbase': str,
    'width': str,
    'year': int
}
